services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 15
      start_period: 40s

  backend:
    build:
      context: .                # root of repo (so .sln + all projects are visible)
      dockerfile: src/Presentation/AuthServer.WebApp/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      # Mount appsettings.json so container sees it at runtime
      - ./src/Presentation/AuthServer.WebApp/appsettings.json:/app/appsettings.json
      - ./src/Presentation/AuthServer.WebApp/appsettings.Development.json:/app/appsettings.Development.json
      - ./src/Presentation/AuthServer.WebApp/wwwroot:/app/wwwroot
    restart: on-failure

  frontend:
    build: ./src/Presentation/AuthServer.WebApp/Client/auth-client
    ports:
      - "4201:80"
    depends_on:
      - backend

volumes:
  sqlserverdata:
